# Generated by Django 3.0.6 on 2020-05-15 11:06
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("afip", "0005_flatten_taxpayer_extras"),
    ]

    operations = [
        migrations.DeleteModel(name="TaxPayerExtras",),
    ]
